apiVersion: apps/v1
kind: Deployment
metadata:
  name: life-track-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: life-track-backend
  template:
    metadata:
      labels:
        app: life-track-backend
    spec:
      containers:
        - name: app
          image: 836881754257.dkr.ecr.ap-northeast-2.amazonaws.com/be_life_track:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: APP_NAME
              value: "Life Track"
            - name: APP_ENV
              value: "development"
            - name: DEBUG
              value: "true"
            - name: DATABASE_URL
              value: "mysql+asyncmy://root:my-secret-pw@mysql-service.default.svc.cluster.local:3306/life_track"
            - name: JWT_SECRET
              value: "cjWA77z57XIkgrIIgwRHCsOuWRhH6mf1"
            - name: JWT_ALGORITHM
              value: "HS256"
            - name: JWT_EXPIRATION_MINUTES
              value: "60"
            - name: LOG_LEVEL
              value: "INFO"
            - name: KAKAO_APP_ID
              value: "1335231"
            - name: PYTHONPATH
              value: "/app"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: life-track-backend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: life-track-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http